name: Check TFT News

on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

# Doğrudan Node 24'ü zorunlu olarak kullanıyoruz
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Sürüm numarası yerine doğrudan ana geliştirme dalını (main) çekiyoruz
      - name: Checkout code
        uses: actions/checkout@main 
        with:
          persist-credentials: true

      # Sürüm numarası yerine doğrudan ana geliştirme dalını (main) çekiyoruz
      - name: Set up Python
        uses: actions/setup-python@main 
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python tft_news.py

      - name: Commit last news update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_news.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last news" && git push)
